name: condition-tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    
    env:
        first: 12
    steps:
    - name: test1
      run: echo hoge
      if: ( first == 12 )

    - name: test2
      run: echo hoge
      if: ( 'a' == 'b' )

    - name: test3
      run: echo hoge
      if: >
        'a' == 'a'
