name: conditions
on:
  push: 
    branches: [workflow]
jobs:
  a-failing-job:
    runs-on: ubuntu-latest
    steps:
    - name: Failing step
      run: exit 1
    - name: Login to Jira
      uses: atlassian/gajira-login@master
      if: failure()
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Create Jira issue on job failure
      uses: atlassian/gajira-create@master
      if: failure()
      with:
        project: DMAC
        issuetype: Bug
        summary: Build failed for ${{ github.repository }}
    - name: Notify Teams
      # You may pin to the exact commit or the version.
      # uses: thechetantalwar/teams-notify@8a78811f5e8f58cdd204efebd79158006428c46b
      uses: thechetantalwar/teams-notify@v2
      if: failure()
      with:
        # WebHook URL of your MS Teams Channel
        teams_webhook_url: https://lntcon.webhook.office.com/webhookb2/e71a30ee-04bf-4f4f-ad14-b36b66791252@264b9899-fe1b-430b-9509-2154878d5774/IncomingWebhook/5fb9c7421c0b4dcc9514ebc39beea13e/9c385632-7bf9-41ac-9e75-fe5f3d846ec2
        # Message to be sent
        message: "Integrated successfully"
        
